pmndrs/drei-vanilla

.storybook/stories/volumetricSpotlight.stories.ts, README.md, src/materials/SpotLightMaterial.ts
Need volume in spotlight
Adding Volumetric spotlight from drei
=> feat: volumetric spotlights

src/materials/MeshTransmissionMaterial.ts
options could not be passed in the constructor
accept all uniforms in the contructor
=> Mesh Transmission material accept all parameters in a object

.storybook/stories/AccumulativeShadows.stories.ts, README.md, src/core/AccumulativeShadows.ts, src/core/index.ts
New feat
Adding Accumulative Shadows
=> Accumulative Shadows

.storybook/stories/Grid.stories.ts, README.md, src/core/Grid.ts, src/core/index.ts
=> feat: add grid gizmo

src/core/Grid.ts, src/core/useFBO.ts
Not passing optional parameter was giving typescript error
Added default values so everyone's happy
=> fix :Use fbo typescript parameter fix

.storybook/stories/MeshTransmissionMaterial.stories.ts
values were being set on discard material
ensure values are not set on discard material
=> fix: mtm typo fix

src/materials/BlurPass.ts
Remove three js warning
use same code from drei
=> fix: blurpass encoding

.storybook/stories/MeshTransmissionMaterial.stories.ts, src/materials/MeshTransmissionMaterial.ts
MTM params were not optional and gave an error when nothing was passed
Fixed the issue and updated the story book
=> fix: mtm params are optional

.storybook/stories/Outlines.stories.ts, README.md, src/core/Outlines.ts, src/core/index.ts
=> feat: introducing `Outlines`

.storybook/stories/Billboard.stories.ts, README.md, src/core/Billboard.ts
Port the `Billboard` of `@pmndrs/drei`.
=> feat: introducing the `Billboard`

package.json, yarn.lock
update three version
going to 0.152.0
=> docs: update three to 0.152.0

.storybook/Setup.ts, .storybook/stories/AccumulativeShadows.stories.ts, .storybook/stories/Billboard.stories.ts, .storybook/stories/Caustics.stories.ts, .storybook/stories/Grid.stories.ts, .storybook/stories/MeshReflectorMaterial.stories.ts, .storybook/stories/MeshTransmissionMaterial.stories.ts, .storybook/stories/Outlines.stories.ts, .storybook/stories/PCSS.stories.ts, .storybook/stories/shaderMaterial.stories.ts, .storybook/stories/volumetricSpotlight.stories.ts, src/core/AccumulativeShadows.ts, src/core/Caustics.ts
lots of warnings in the console after updating three
fix all the encoding related issues and update the stories for better look
=> fix: all console warnings

.storybook/stories/Outlines.stories.ts, README.md, src/core/Outlines.ts
"render" word was confusing , users might add it to the render loop
"rename" render to "generate" to match the action better
=> fix: rename render to generate in outlines

README.md, src/core/index.ts
The missing `export` and docs.
I was stupid. 🥲
=> fix: the missing export and docs

package.json
Installation error when troika was not installed
moved it to deps
=> fix: move troika to dependencies 

.storybook/stories/Splat.stories.ts, src/core/Splat.ts
Storybook camera no at correct pos
fix storybook camera, remove unused vars froms splat.ts
=> fix: remove unused vars, storybook cam fix

src/core/pcss.ts
resolve  https://github.com/pmndrs/drei-vanilla/issues/50
handle array also
=> PCSS handle array materials in reset function

src/materials/MeshTransmissionMaterial.ts
=> fix: mtm roughness fix from drei

.storybook/stories/Clouds.stories.ts, README.md, src/core/Cloud.ts
updateClouds to updateCloud as this falls under the Cloud Class and not the Clouds class
=> fix: rename updateClouds to updateCloud

README.md
tried to copy paste docs example and it didn't work 
so I checked the storybook example and found the right way
=> docs: fix billboard

.storybook/stories/Outlines.stories.ts, README.md, src/core/Outlines.ts
Because I want this.
Update `Outline` to latest version of it's drei counterpart, which adds `screenspace` support.
=> feat: add screenspace to Outline

src/core/Cloud.ts
Error On android `Program Info Log: Name conflicts between an uniform and an attribute: opacity` https://github.com/pmndrs/drei-vanilla/issues/71
rename `opacity` attribute to `cloudOpacity` and update all usage
=> Clouds rename attribute with same name

.storybook/Setup.ts, .storybook/stories/MeshPortalMaterial.stories.ts, .storybook/stories/MeshPortalMaterialSdf.stories.ts, README.md, package.json, src/core/MeshPortalMaterial.ts, src/core/index.ts, src/helpers/constants.ts, yarn.lock
=> feat: add meshPortalMaterial

.storybook/stories/volumetricSpotlight.stories.ts, src/materials/SpotLightMaterial.ts
=> Spotlight shader code update + example fix

.github/workflows/release.yml, src/materials/SpotLightMaterial.ts
Release fails
Update upload-artifact version
=> Update upload artifact ver

.github/workflows/release.yml
Release job fails
downgrade upload artifact version
=> chore: downgrade upload-pages-artifact action to v3

.storybook/stories/Sparkles.stories.ts, README.md, src/core/Sparkles.ts, src/core/index.ts
=> feat: add Sparkles

.storybook/stories/Stars.stories.ts, README.md, src/core/Stars.ts, src/core/index.ts
=> feat: add Stars 
